#!/bin/bash

shopt -s globstar nullglob

for file in **/*.gif; do
  if [[ -f "$file" ]]; then
    filename=$(basename -- "$file")
    filename="${filename%.*}"
    echo "$filename"
  fi
done | LC_COLLATE=C sort -f

echo

